In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import numpy as np
from hilbert import decode, encode
from tqdm import tqdm
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
df = pd.read_parquet("data/F_BTCUSDT_1m.parquet")
tc = ["Open",
"High",
"Low",
"Close",
"Volume"]
for i in tc:
    df[i]=df[i].astype("float")

In [221]:
data = np.array(range(32*32))
locs = decode(data, 2, 5)
hilbert_list = []
target_list = []
target_list_real = []


for i in tqdm(range(32*32,len(df),10)):
    temp_f = df.iloc[i-32*32:i]
    #temp_t_5 = df.iloc[i:i+5]
    #temp_t_10 = df.iloc[i+5:i+10]
    temp_t_15 = df.iloc[i:i+15]
    #temp_t_20 = df.iloc[i+15:i+20]
    
    if len(temp_t_15)<5:
        target_list.append(
        np.array([0,0,0,0,0,0,0,0])
    )
        continue
    
    lv = temp_f.Close.iloc[-1]
    o1 = np.zeros((5,32,32))
    vals = temp_t_15[["Open","High","Low","Close","Volume"]].values
    target_list_real.append(temp_t_15[["Open","High","Low","Close"]].values)
    vals[:,:4]=(vals[:,:4]-vals[:,2].min())/(vals[:,1].max()-vals[:,2].min())
    vals[:,4]=(vals[:,4]-vals[:,4].min())/(vals[:,4].max()-vals[:,4].min())
    #for j in range(len(data)):
    #    o1[:,locs[j][0],locs[j][1]] = vals[j]

#    hilbert_list.append(o1)
    target_list.append(vals)
    
    """target_list.append(
        np.array(
            [
                (temp_t_5.Low.min()/lv)-1,(temp_t_5.High.max()/lv)-1,
                (temp_t_10.Low.min()/lv)-1,(temp_t_10.High.max()/lv)-1,
                (temp_t_15.Low.min()/lv)-1,(temp_t_15.High.max()/lv)-1,
                (temp_t_20.Low.min()/lv)-1,(temp_t_20.High.max()/lv)-1
            ]
        )
    )"""
    

 47%|███████████████▉                  | 74374/158298 [00:46<00:54, 1549.92it/s]/tmp/ipykernel_4140/2372953184.py:25: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:26: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:25: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:26: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:25: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:26: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:25: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:26: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:25: RuntimeWarning:

invalid value encountered in true_divide

/tmp/ipykernel_4140/2372953184.py:26: RuntimeWa

In [222]:
target_list_real[-1]=target_list_real[-2]

In [223]:
target_list = [i.flatten() for i in target_list]

In [224]:
target_list[-1]=target_list[-2]

In [225]:
target_list = [i.reshape(1,*i.shape) for i in target_list]

In [226]:
tla = np.concatenate(target_list,axis=0)

In [227]:
tla.shape

(158298, 75)

In [45]:
tla = tla.reshape(tla.shape[0],tla.shape[1]*tla.shape[2])

In [46]:
tla.shape

(158298, 75)

In [8]:
h1=temp_t_15["High"].iloc[0]
h2=temp_t_15["High"].iloc[7]
h3=temp_t_15["High"].iloc[14]
ha = (((h2/h1)-1)+((h3/h2)-1))/2
l1=temp_t_15["Low"].iloc[0]
l2=temp_t_15["Low"].iloc[7]
l3=temp_t_15["Low"].iloc[14]
la = (((l2/l1)-1)+((l3/l2)-1))/2
la,ha

(-0.0020184114768714845, -0.0018619093889628013)

In [5]:
target_df = pd.DataFrame(target_list,columns=["Low_5","High_5","Low_10","High_10","Low_15","High_15","Low_20","High_20"])

In [59]:
target_df.iloc[-1]=target_df.iloc[-2]

In [18]:
target_df["Low_slope"] = ((-((target_df.Low_10/target_df.Low_5)-1)) + (-((target_df.Low_15/target_df.Low_10)-1)) + (-((target_df.Low_20/target_df.Low_15)-1)))/3
target_df["High_slope"] = ((((target_df.High_10/target_df.High_5)-1)) + (((target_df.High_15/target_df.High_10)-1)) + (((target_df.High_20/target_df.High_15)-1)))/3


In [42]:
tdf2 = (tdf2-tdf2.values.mean())/tdf2.values.std()

In [44]:
target_df = tdf1.join(tdf2)

In [4]:
hlt = np.array(hilbert_list)

In [5]:
ohlc = hlt[:,:4,:,:]
vol = hlt[:,-1:,:,:]

In [6]:
ohlc.mean(),ohlc.std(),vol.mean(),vol.std()

(28001.938870730588, 17834.47169281324, 248.00923831004107, 426.5438396373735)

In [5]:
ohlc = (ohlc-ohlc.mean())/ohlc.std()
vol = (vol-vol.mean())/vol.std()
hltn = np.concatenate((ohlc,vol),axis=1)
hltn.shape

In [6]:
hltn = np.concatenate((ohlc,vol),axis=1)
hltn.shape

(158298, 5, 32, 32)

In [61]:
#hlt = (hlt-hlt.mean())/hlt.std()
div = int(len(target_list)*0.9)
#for i,j in tqdm(enumerate(hltn)):
#    if i<div:
#        np.save('imgs/train_4layer_w_volume/%07d.npy'%i,j)
#    else:
#        np.save('imgs/test_4layer_w_volume/%07d.npy'%i,j) 
target_df["label"] = target_df.index.to_list()
target_df["label"] = target_df.label.apply(lambda x:"%07d.npy"%x)
target_df.iloc[:div].to_parquet("imgs/train_4layer_w_volume/target_line_3.parquet")
target_df.iloc[div:].to_parquet("imgs/test_4layer_w_volume/target_line_3.parquet")

In [228]:
tla = np.nan_to_num(tla)

In [229]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=20, random_state=0).fit_predict(tla)


In [38]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=0).fit_predict(target_df.iloc[:,:-2].values)


In [55]:
np.unique(kmeans,return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19], dtype=int32),
 array([7961, 8348, 9492, 9549, 8612, 7651, 6564, 8356, 9797, 5913, 8325,
        8082, 8413, 5892, 7545, 7637, 7875, 6932, 6296, 9058]))

In [230]:
dfc = pd.DataFrame(tla)
dfc["label"] = kmeans

In [231]:
dsc = dfc.groupby("label").describe()

In [232]:
col_list = []
for i,j in enumerate(dsc.columns):
    if j[0]%5==0:
        val="Open"
    if j[0]%5==1:
        val="High"
    if j[0]%5==2:
        val="Low"
    if j[0]%5==3:
        val="Close"
    if j[0]%5==4:
        val="Volume"
    col_list.append(val+"_"+str((j[0]//5)+1)+"_"+j[1]) 

In [233]:
dsc.columns=col_list

In [101]:
dsc.to_parquet("20_cluster_desc.parquet")

In [41]:
target_df["labels"]=kmeans

In [30]:
tla

array([[8.35472e+03, 8.35595e+03, 8.35375e+03, ..., 8.32005e+03,
        8.32485e+03, 1.77890e+01],
       [8.32041e+03, 8.32497e+03, 8.31904e+03, ..., 8.31423e+03,
        8.32200e+03, 2.34280e+01],
       [8.34404e+03, 8.34854e+03, 8.34167e+03, ..., 8.33611e+03,
        8.34186e+03, 5.41500e+00],
       ...,
       [2.03035e+04, 2.03150e+04, 2.03010e+04, ..., 2.03332e+04,
        2.03362e+04, 2.18129e+02],
       [2.03253e+04, 2.03253e+04, 2.03021e+04, ..., 2.03299e+04,
        2.03440e+04, 5.95273e+02],
       [2.03253e+04, 2.03253e+04, 2.03021e+04, ..., 2.03299e+04,
        2.03440e+04, 5.95273e+02]])

In [84]:
dsc = pd.read_parquet("20_cluster_desc.parquet")

In [153]:
np.array([ta[[j+"_"+str(i)+"_mean" for i in range(1,16)]].to_list() for j in ["Open","High","Low","Close"]]).transpose()

array([[1.00000014, 1.00050549, 0.99949736, 0.99999538],
       [0.99999523, 1.0005439 , 0.99945056, 0.99998758],
       [0.99998758, 1.00049886, 0.99948234, 0.99999244],
       [0.99999257, 1.00049624, 0.99949488, 0.999985  ],
       [0.99998534, 1.00047494, 0.99949247, 0.99997734],
       [0.99997688, 1.00046857, 0.99949614, 0.99997232],
       [0.99997212, 1.00053876, 0.9994444 , 0.99999348],
       [0.99999371, 1.00049089, 0.99946937, 0.99996677],
       [0.99996704, 1.00046886, 0.99943501, 0.99993834],
       [0.99993799, 1.00054706, 0.9992615 , 0.99987931],
       [0.99988027, 1.00103297, 0.99867024, 0.99990395],
       [0.99990301, 1.00071938, 0.99915947, 0.99995427],
       [0.99995398, 1.00057096, 0.99931628, 0.99993812],
       [0.99993745, 1.00050631, 0.99934598, 0.9999205 ],
       [0.99992095, 1.00047462, 0.99936369, 0.99990515]])

In [209]:
target_list_real[46]

array([[8312.87, 8314.38, 8308.51, 8310.  ],
       [8306.86, 8310.91, 8306.86, 8308.02],
       [8310.24, 8315.68, 8306.86, 8312.32],
       [8312.22, 8312.48, 8309.09, 8309.09],
       [8311.62, 8311.62, 8308.28, 8309.47],
       [8309.39, 8309.76, 8306.86, 8306.86],
       [8308.92, 8308.92, 8303.1 , 8304.64],
       [8304.64, 8308.  , 8276.37, 8279.02],
       [8276.35, 8290.53, 8275.81, 8283.14],
       [8281.51, 8285.56, 8279.73, 8282.78],
       [8282.53, 8284.75, 8280.38, 8281.05],
       [8281.21, 8287.36, 8279.32, 8286.7 ],
       [8287.57, 8292.07, 8286.79, 8292.07],
       [8290.96, 8294.93, 8289.08, 8292.68],
       [8289.08, 8291.02, 8285.23, 8287.82]])

0         1         2         3         4         5         6  \
46      0.000032  0.000214 -0.000492 -0.000313  0.144588 -0.000691 -0.000203   
65     -0.000019  0.000096 -0.000167 -0.000167  0.000000 -0.000213 -0.000055   
99      0.000000  0.000361 -0.000755 -0.000659  0.389485 -0.000659 -0.000414   
101     0.000037  0.000683  0.000037  0.000683  0.000000  0.000666  0.000688   
102    -0.000001 -0.000001 -0.001000 -0.000904  0.020314 -0.000835 -0.000500   
...          ...       ...       ...       ...       ...       ...       ...   
158248 -0.000005  0.000151 -0.000321 -0.000321  0.003852 -0.000316 -0.000110   
158249  0.000005  0.001259  0.000000  0.001003  0.053750  0.000998  0.001681   
158255  0.000000  0.000538 -0.000289  0.000145  0.008799  0.000145  0.000329   
158279  0.000000  0.000120 -0.000390 -0.000275  0.146781 -0.000270  0.000010   
158286  0.000000  0.000303 -0.000149  0.000134  0.078414  0.000134  0.000134   

               7         8         9        10        11        12        13  \
46     -0.000691 -0.000551  0.040120 -0.000284  0.000371 -0.000691 -0.000034   
65     -0.000465 -0.000055  0.441366 -0.000092 -0.000092 -0.001601 -0.001423   
99     -0.001170 -0.000653  0.000000 -0.000659  0.000213 -0.000864  0.000071   
101     0.000275  0.000676  0.053994  0.000322  0.000610 -0.000043  0.000225   
102    -0.001025 -0.000503  0.245086 -0.000503 -0.000503 -0.000792 -0.000650   
...          ...       ...       ...       ...       ...       ...       ...   
158248 -0.000703 -0.000216  0.061611 -0.000211 -0.000070 -0.000452 -0.000151   
158249  0.000998  0.001209  0.058174  0.001204  0.001615  0.000707  0.001385   
158255 -0.000344  0.000060  0.013760  0.000060  0.000927  0.000060  0.000394   
158279 -0.000400 -0.000130  0.063694 -0.000130  0.000899 -0.000160  0.000485   
158286 -0.000308 -0.000114  0.009203 -0.000109 -0.000109 -0.000905 -0.000607   

              14        15        16        17        18        19        20  \
46      0.287935 -0.000046 -0.000014 -0.000422 -0.000422  0.078183 -0.000118   
65      0.222120 -0.001410 -0.000952 -0.001440 -0.000953  0.045046 -0.001186   
99      0.042634  0.000086  0.001673  0.000086  0.001316  0.458240  0.001341   
101     0.051962 -0.000043  0.000289 -0.000074 -0.000044  0.034078 -0.000044   
102     0.000000 -0.000650  0.000040 -0.000650  0.000040  0.345371  0.000040   
...          ...       ...       ...       ...       ...       ...       ...   
158248  0.025914 -0.000146  0.000166 -0.000226  0.000161  0.051671  0.000166   
158249  0.027947  0.001380  0.001425  0.000928  0.001420  0.007486  0.001425   
158255  0.000564  0.000389  0.001415  0.000125  0.001415  0.001782  0.001415   
158279  0.083148  0.000485  0.000884  0.000215  0.000215  0.075556  0.000220   
158286  0.198033 -0.000607 -0.000607 -0.001701 -0.001701  0.505930 -0.001701   

              21        22        23        24        25        26        27  \
46     -0.000118 -0.000520 -0.000377  0.084020 -0.000386 -0.000342 -0.000691   
65     -0.000681 -0.001299 -0.001064  0.184876 -0.001136 -0.001136 -0.002030   
99      0.001469  0.000647  0.000847  0.299809  0.000676  0.000676 -0.000166   
101    -0.000044 -0.000135 -0.000044  0.006959 -0.000044  0.001479 -0.000135   
102     0.000583  0.000034  0.000545  0.247521  0.000403  0.000403 -0.000204   
...          ...       ...       ...       ...       ...       ...       ...   
158248  0.000422 -0.000166  0.000417  0.000000  0.000422  0.000944  0.000191   
158249  0.001896  0.001400  0.001896  0.051115  0.001896  0.002122  0.001655   
158255  0.001480  0.000528  0.000822  0.000554  0.000817  0.001525  0.000782   
158279  0.000555  0.000215  0.000405  0.000000  0.000405  0.000505 -0.000185   
158286 -0.000781 -0.002179 -0.001229  0.803182 -0.001234 -0.001229 -0.001736   

              28        29        30        31        32        33        34  \
46     -0.000691  0.000000 -0.000443 -0.000443 -0.001143 -0.000958  0.285921   
65     -0.0

In [234]:
dsc

Open_1_count  Open_1_mean  Open_1_std  Open_1_min  Open_1_25%  \
label                                                                  
0            8155.0     0.727485    0.249074    0.000000    0.563691   
1            7956.0     0.774530    0.184484    0.000000    0.656835   
2            9497.0     0.217101    0.164945    0.000000    0.078308   
3            8212.0     0.260103    0.244281    0.000000    0.046388   
4            6834.0     0.716991    0.208588    0.000000    0.579754   
5            6169.0     0.271804    0.199306    0.000000    0.105882   
6           10088.0     0.806580    0.155332    0.007348    0.704152   
7            7437.0     0.389327    0.232298    0.000000    0.211957   
8            9460.0     0.770524    0.166916    0.034155    0.658921   
9            7927.0     0.221140    0.186569    0.000000    0.061658   
10           8367.0     0.827752    0.157068    0.001248    0.739150   
11           7618.0     0.347744    0.216901    0.000000    0.177146   
12           7753.0     0.592471    0.233543    0.000000    0.432686   
13           6233.0     0.738608    0.198779    0.000000    0.611781   
14          10180.0     0.195451    0.156346    0.000000    0.065359   
15           6886.0     0.793243    0.156602    0.133836    0.689111   
16           6948.0     0.212353    0.158617    0.000000    0.082444   
17           8252.0     0.185399    0.165997    0.000000    0.045768   
18           6506.0     0.299514    0.208797    0.000000    0.132186   
19           7820.0     0.654515    0.212253    0.000000    0.516341   

       Open_1_50%  Open_1_75%  Open_1_max  High_1_count  High_1_mean  \
label                                                                  
0        0.792444    0.946162    1.000000        8155.0     0.908178   
1        0.809497    0.928661    1.000000        7956.0     0.909287   
2        0.191045    0.328341    1.000000        9497.0     0.313663   
3        0.192395    0.422864    1.000000        8212.0     0.435460   
4        0.748985    0.886763    1.000000        6834.0     0.844827   
5        0.248786    0.401053    1.000000        6169.0     0.403671   
6        0.837404    0.936130    1.000000       10088.0     0.905913   
7        0.389648    0.551237    1.000000        7437.0     0.544539   
8        0.795170    0.907356    1.000000        9460.0     0.862311   
9        0.185484    0.339691    1.000000        7927.0     0.361208   
10       0.867591    0.955629    1.000000        8367.0     0.930329   
11       0.338731    0.494203    1.000000        7618.0     0.521461   
12       0.594172    0.767168    1.000000        7753.0     0.742680   
13       0.770000    0.903120    1.000000        6233.0     0.854962   
14       0.165232    0.298709    1.000000       10180.0     0.293924   
15       0.820035    0.922860    1.000000        6886.0     0.877010   
16       0.187950    0.314688    1.000000        6948.0     0.305107   
17       0.147813    0.284403    0.998686        8252.0     0.296183   
18       0.275431    0.440803    1.000000        6506.0     0.439917   
19       0.658891    0.818594    1.000000        7820.0     0.786850   

       High_1_std  High_1_min  High_1_25%  High_1_50%  High_1_75%  High_1_max  \
label                                                                           
0        0.159107    0.084205    0.860382    1.000000    1.000000         1.0   
1        0.120972    0.309412    0.839951    0.978124    1.000000         1.0   
2        0.168041    0.002271    0.178868    0.296669    0.431553         1.0   
3        0.217101    0.001538    0.268719    0.406810    0.575275         1.0   
4        0.152922    0.228230    0.738904    0.881200    0.999487         1.0   
5        0.200043    0.000625    0.251893    0.381295    0.533812         1.0   
6        0.114191    0.466092    0.837935    0.955692    1.000000         1.0   
7        0.203702    0.000569    0.401453    0.545265    0.681834         1.0   
8        0.134384    0.1711

In [253]:
idcs = list(dfc[dfc.label==0].index )

In [254]:
idcs

[3,
 36,
 42,
 70,
 91,
 134,
 135,
 140,
 154,
 177,
 232,
 262,
 266,
 298,
 301,
 304,
 343,
 345,
 346,
 362,
 384,
 441,
 459,
 469,
 517,
 520,
 595,
 617,
 621,
 625,
 673,
 693,
 729,
 741,
 795,
 802,
 811,
 838,
 842,
 860,
 864,
 872,
 897,
 972,
 1003,
 1033,
 1040,
 1063,
 1090,
 1123,
 1162,
 1176,
 1178,
 1197,
 1215,
 1222,
 1351,
 1368,
 1371,
 1377,
 1381,
 1393,
 1477,
 1482,
 1493,
 1510,
 1570,
 1591,
 1618,
 1621,
 1663,
 1677,
 1687,
 1706,
 1721,
 1726,
 1732,
 1735,
 1808,
 1812,
 1825,
 1836,
 1882,
 1918,
 1937,
 1958,
 1973,
 1986,
 1989,
 2002,
 2017,
 2025,
 2073,
 2083,
 2088,
 2097,
 2105,
 2108,
 2124,
 2136,
 2185,
 2231,
 2237,
 2249,
 2264,
 2271,
 2278,
 2282,
 2320,
 2353,
 2364,
 2376,
 2378,
 2410,
 2415,
 2438,
 2444,
 2462,
 2510,
 2512,
 2517,
 2566,
 2569,
 2592,
 2601,
 2620,
 2622,
 2631,
 2632,
 2661,
 2665,
 2680,
 2702,
 2721,
 2751,
 2755,
 2805,
 2812,
 2835,
 2866,
 2880,
 2890,
 2914,
 2927,
 2936,
 2956,
 2964,
 2978,
 2982,
 2994,


In [266]:
np.concatenate(target_list_real).max()

69198.7

In [280]:
pd.DataFrame([[target_list_real[i][0,0]/target_list_real[i].min(),target_list_real[i].max()/target_list_real[i][0,0]] for i in idcs]).describe()

0            1
count  9497.000000  9497.000000
mean      1.001192     1.005122
std       0.001389     0.005510
min       1.000000     1.000000
25%       1.000355     1.002174
50%       1.000836     1.003585
75%       1.001563     1.006035
max       1.024757     1.091107

In [279]:
label_i = 2
ta = dsc.loc[label_i]
idcs = list(dfc[dfc.label==label_i].index )
to_plot = pd.DataFrame(np.array([ta[[j+"_"+str(i)+"_mean" for i in range(1,16)]].to_list() for j in ["Open","High","Low","Close"]]).transpose(),columns=["Open","High","Low","Close"])
to_plot = to_plot
to_plot["time"]=range(1,16)
fig1 = go.Figure(data=go.Ohlc(x=to_plot['time'],
                             open=to_plot['Open'],
                             high=to_plot['High'],
                             low=to_plot['Low'],
                             close=to_plot['Close']))
  
# show the figure
fig1.update(layout_xaxis_rangeslider_visible=False)
fig1.show()
for i in range(10):
    print(idcs[i*len(idcs)//10])
    real_vals = target_list_real[idcs[i*len(idcs)//10]]
    print(real_vals[0,0]/real_vals.min(),real_vals.max()/real_vals[0,0])
    to_plot_real = pd.DataFrame(real_vals,columns=["Open","High","Low","Close"])
    to_plot_real["time"]=range(1,16)
    fig = go.Figure(data=go.Ohlc(x=to_plot_real['time'],
                                 open=to_plot_real['Open'],
                                 high=to_plot_real['High'],
                                 low=to_plot_real['Low'],
                                 close=to_plot_real['Close']))

    # show the figure
    fig.update(layout_xaxis_rangeslider_visible=False)
    fig.show()


14
1.0005059666901268 1.0124773958049968


15563
1.001103505665642 1.0039054470709148


31343
1.0008832499152858 1.0040182932244028


47271
1.0000929406859365 1.0012788814050644


62226
1.0000005237933112 1.003063665472244


78327
1.0026142624668228 1.002739115093088


95624
1.0001057498131751 1.006702523811426


112315
1.0013126464191746 1.0098489558987707


129056
1.001262039860267 1.00301499430277


144251
1.0007975912743514 1.0034567950429358


In [270]:
20150/20060,39780/39620

(1.0044865403788634, 1.0040383644623927)

In [250]:
import plotly.graph_objects as go
  
# import python pandas package
import pandas as pd
  
# read the stock price dataset
  
# use go.OHLC function and pass the date, open,
# high, low and close price of the function


In [ ]:
from matplotlib.finance import candlestick2_ohlc
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import datetime as datetime
import numpy as np

quotes = np.array(...)

fig, ax = plt.subplots()
candlestick2_ohlc(ax,quotes['open'],quotes['high'],quotes['low'],quotes['close'],width=0.6)

xdate = [datetime.datetime.fromtimestamp(i) for i in quotes['time']]

ax.xaxis.set_major_locator(ticker.MaxNLocator(6))

def mydate(x,pos):
    try:
        return xdate[int(x)]
    except IndexError:
        return ''

ax.xaxis.set_major_formatter(ticker.FuncFormatter(mydate))

fig.autofmt_xdate()
fig.tight_layout()

plt.show()